#spring:
#  data:
#    mongodb:
#      uri: mongodb://172.21.213.33/MapArchiveDB


resourcePath: Z:/resources

mbtilesPath: Z:/mbtiles

terrariumPath: Y:/mbtiles

deployIpAndPort: 172.21.212.240:9000

